export const SHIPMENT_TAG_AFTER_WEIGHT = "SHIPMENT_TAG_AFTER_WEIGHT";
export const SHIPMENT_TAG_ACCEPT_CARGO = "SHIPMENT_TAG_ACCEPT_CARGO";
export const SHIPMANT_TAG_SMALL_STICK = "SHIPMANT_TAG_SMALL_STICK";
